=== GonJunLor/108LMSGIProyectoLMSGI/examenes/Ex1ev02/libro.dtd
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT subgenero (#PCDATA)>
<!ELEMENT tituloOriginal (#PCDATA)>
<!ELEMENT autor (nombre,apellido)>
<!ELEMENT libro (titulo,autor,genero,subgenero,tituloOriginal)>
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro genero CDATA #IMPLIED>
<!ATTLIST libro idioma CDATA "Español">
<!ATTLIST libro formato (impreso|digital) "impreso">
<!ATTLIST libro referencia IDREFS #IMPLIED>
<!ELEMENT biblioteca (libro+)>

=== GonJunLor/108LMSGIProyectoLMSGI/examenes/Ex1ev02/libro.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Nombre: 
    Descripción Información de un email 
    Fecha de modificación 02/12/2024-->
<!DOCTYPE biblioteca SYSTEM "libro.dtd">
<biblioteca>
    <libro id="Libro1" genero="novela">
        <titulo>Punto para los locos</titulo>
        <autor>
            <nombre>Susanze</nombre>
            <apellido>Collins</apellido>
        </autor>
        <genero>Novela</genero>
        <subgenero>Ciencia ficción, aventura, juvenil</subgenero>
        <tituloOriginal>The Hunger games</tituloOriginal>
    </libro>
</biblioteca>
