=== GonJunLor/108LMSGIProyectoLMSGI/ud4/04/04.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT universidad (nombre,fechaconstruccion,pais,carreras,asignaturas,alumnos)>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre year CDATA #IMPLIED>
<!ELEMENT fechaconstruccion (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT carreras (carrera)+>
<!ELEMENT carrera (nombre?,plan?,creditos?,centro?,subdirector?,asignaturas?)>
<!ATTLIST carrera 
id ID #IMPLIED
codigo IDREF #IMPLIED>
<!ELEMENT plan (#PCDATA)>
<!ELEMENT creditos (#PCDATA)>
<!ELEMENT centro (#PCDATA)>
<!ELEMENT subdirector (#PCDATA)>
<!ELEMENT asignaturas (asignatura)+>
<!ELEMENT asignatura (nombre,creditos_teoricos,creditos_practicos,trimestre)?>
<!ATTLIST asignatura 
id ID #IMPLIED
titulacion IDREF #IMPLIED
codigo IDREF #IMPLIED>
<!ELEMENT creditos_teoricos (#PCDATA)>
<!ELEMENT creditos_practicos (#PCDATA)>
<!ELEMENT trimestre (#PCDATA)>
<!ELEMENT alumnos (alumno)*>
<!ELEMENT alumno (apellido1,apellido2,nombre,sexo,estudios)>
<!ATTLIST alumno 
id ID #REQUIRED
beca (si) #IMPLIED>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT estudios (carrera,asignaturas,proyecto?)>
<!ELEMENT proyecto (#PCDATA)>

=== GonJunLor/108LMSGIProyectoLMSGI/ud4/04/04.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE universidad SYSTEM "04.dtd">
<universidad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="04.xsd">

    <nombre year="1964">Universidad de Victoria</nombre>
	<fechaconstruccion>14/03/1964</fechaconstruccion>
    <pais>España</pais>

<!-- CARRERAS -->

    <carreras>

        <carrera id="c01">
            <nombre>I.T. Informática</nombre>
            <plan>2003</plan>
            <creditos>250</creditos>
            <centro>Escuela de Informática</centro>
        </carrera>

        <carrera id="c02">
            <nombre>Dipl. Empresariales</nombre>
            <plan>2001</plan>
            <creditos>275</creditos>
            <centro>Facultad de Ciencias Sociales</centro>
        </carrera>

        <carrera id="c03">
            <nombre>Dipl. Relaciones Laborales</nombre>
            <plan>2001</plan>
            <creditos>280</creditos>
            <centro>Facultad de Ciencias Sociales</centro>
            <subdirector>Alfonso Martín  Luque</subdirector>
        </carrera>

        <carrera id="c04">
            <nombre>Lic. Quimica</nombre>
            <plan>2003</plan>
            <creditos>175</creditos>
            <centro>Facultad de Ciencias Experimentales</centro>
        </carrera>

        <carrera id="c05">
            <nombre>Lic. Biología</nombre>
            <plan>2001</plan>
            <creditos>175</creditos>
            <centro>Facultad de Ciencias Experimentales</centro>
        </carrera>

        <carrera id="c06">
            <nombre>Lic. Humanidades</nombre>
            <plan>1980</plan>
            <creditos>475</creditos>
            <centro>Facultad de Humanidades</centro>
        </carrera>

    </carreras>

<!-- ASIGNATURAS -->

    <asignaturas>

        <asignatura id="a01" titulacion="c01">
            <nombre>Ofimática</nombre>
            <creditos_teoricos>3</creditos_teoricos>
            <creditos_practicos>1.5</creditos_practicos>
            <trimestre>1</trimestre>
        </asignatura>

        <asignatura id="a02" titulacion="c01">
            <nombre>Ingeniería del Software</nombre>
            <creditos_teoricos>6</creditos_teoricos>
            <creditos_practicos>1.5</creditos_practicos>
            <trimestre>2</trimestre>
        </asignatura>

        <asignatura id="a03" titulacion="c02">
            <nombre>Administración de Empresas</nombre>
            <creditos_teoricos>4</creditos_teoricos>
            <creditos_practicos>1.5</creditos_practicos>
            <trimestre>1</trimestre>
        </asignatura>

        <asignatura id="a04" titulacion="c02">
            <nombre>Derecho Internacional</nombre>
            <creditos_teoricos>4</creditos_teoricos>
            <creditos_practicos>5</creditos_practicos>
            <trimestre>1</trimestre>
        </asignatura>

        <asignatura id="a05" titulacion="c04">
            <nombre>Pedagogía</nombre>
            <creditos_teoricos>4</creditos_teoricos>
            <creditos_practicos>1.5</creditos_practicos>
            <trimestre>2</trimestre>
        </asignatura>

        <asignatura id="a06" titulacion="c03">
            <nombre>Didáctica</nombre>
            <creditos_teoricos>4</creditos_teoricos>
            <creditos_practicos>3</creditos_practicos>
            <trimestre>2</trimestre>
        </asignatura>

        <asignatura id="a07" titulacion="c04">
            <nombre>Tecnología de los Alimentos</nombre>
            <creditos_teoricos>1.5</creditos_teoricos>
            <creditos_practicos>7.5</creditos_practicos>
            <trimestre>2</trimestre>
        </asignatura>

        <asignatura id="a08" titulacion="c01">
            <nombre>Bases de Datos</nombre>
            <creditos_teoricos>4.5</creditos_teoricos>
            <creditos_practicos>5.5</creditos_practicos>
            <trimestre>1</trimestre>
        </asignatura>

        <asignatura id="a09" titulacion="c06">
            <nombre>Historia del Pensamiento</nombre>
            <creditos_teoricos>6</creditos_teoricos>
            <creditos_practicos>0</creditos_practicos>
            <trimestre>2</trimestre>
        </asignatura>

    </asignaturas>

<!-- ALUMNOS -->

    <alumnos>

        <alumno id="e01">
            <apellido1>Rivas</apellido1>
            <apellido2>Santos</apellido2>
            <nombre>Víctor Manuel</nombre>
            <sexo>Hombre</sexo>
            <estudios>
                <carrera codigo="c01"/>
                <asignaturas>
                    <asignatura codigo="a01"/>
                    <asignatura codigo="a03"/>
                    <asignatura codigo="a05"/>
                    <asignatura codigo="a09"/>
                </asignaturas>
            </estudios>
        </alumno>

        <alumno id="e02">
            <apellido1>Pérez</apellido1>
            <apellido2>García</apellido2>
            <nombre>Luisa</nombre>
            <sexo>Mujer</sexo>
            <estudios>
                <carrera codigo="c02"/>
                <asignaturas>
                    <asignatura codigo="a02"/>
                    <asignatura codigo="a01"/>
                </asignaturas>
                <proyecto>Web de IBM.com</proyecto>
            </estudios>

        </alumno>

        <alumno id="e03" beca="si">
            <apellido1>Pérez</apellido1>
            <apellido2>Romero</apellido2>
            <nombre>Fernando</nombre>
            <sexo>Hombre</sexo>
            <estudios>
                <carrera codigo="c02"/>
                <asignaturas>
                    <asignatura codigo="a02"/>
                    <asignatura codigo="a01"/>
                    <asignatura codigo="a04"/>
                    <asignatura codigo="a09"/>
                </asignaturas>
            </estudios>
        </alumno>

        <alumno id="e04">
            <apellido1>Avalón</apellido1>
            <apellido2>Jiménez</apellido2>
            <nombre>María</nombre>
            <sexo>Mujer</sexo>
            <estudios>
                <carrera codigo="c01"/>
                <asignaturas>
                    <asignatura codigo="a02"/>
                    <asignatura codigo="a01"/>
                    <asignatura codigo="a07"/>
                </asignaturas>
                <proyecto>Estudio de Salinidad del Pantano Iris</proyecto>
            </estudios>
        </alumno>

    </alumnos>

</universidad>
