=== GonJunLor/108LMSGIProyectoLMSGI/ud4/03/03.dtd
<!ELEMENT example (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT lenguaje (description,example)>
<!ELEMENT programmingLanguages (lenguaje)+>
<!ATTLIST lenguaje name CDATA #REQUIRED>

=== GonJunLor/108LMSGIProyectoLMSGI/ud4/03/03.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Nombre: 
    Descripción Información de un email 
    Fecha de modificación 02/12/2024-->
<!DOCTYPE programmingLanguages SYSTEM "03.dtd">
<?xml-stylesheet type="text/css" href="css/estilos.css"?>
<programmingLanguages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="03.xsd">
    <lenguaje name="Python">
        <description>
            Descripción: Python es un lenguaje de programación interpretado, de alto nivel y de propósito general.
        </description>
        <example>
            <![CDATA[  
def saludo():
    print("¡Hola, Mundo!")

saludo()
            ]]>,
        </example>
    </lenguaje>
    <lenguaje name="JavaScript">
        <description>
            Descripción: JavaScript es un lenguaje de programación que se utiliza para crear contenido dinámico en la web.
        </description>
        <example>
            <![CDATA[  
function saludo() {
    alert("¡Hola, Mundo!");
}

saludo();
            ]]>,
        </example>
    </lenguaje>
    <lenguaje name="Java">
        <description>
            Descripción: Java es un lenguaje de programación de propósito general que es ampliamente utilizado en aplicaciones empresariales y móviles.
        </description>
        <example>
            <![CDATA[  
public class Saludo {
    public static void main(String[] args) {
        System.out.println("¡Hola, Mundo!");
    }
}            
            ]]>,
        </example>
    </lenguaje>
    <lenguaje name="C++">
        <description>
            Descripción: C++ es un lenguaje de programación de propósito general, conocido por su eficiencia y uso en aplicaciones de alto rendimiento.
        </description>
        <example>
            <![CDATA[  
#include <iostream>
using namespace std;

int main() {
    cout << "¡Hola, Mundo!" << endl;
    return 0;
}            
            ]]>,
        </example>
    </lenguaje>
    <lenguaje name="Ruby">
        <description>
            Descripción: Ruby es un lenguaje de programación dinámico y de alto nivel, conocido por su sintaxis simple y elegante.
        </description>
        <example>
            <![CDATA[  
def saludo
    puts "¡Hola, Mundo!"
end

saludo            
            ]]>,
        </example>
    </lenguaje>
</programmingLanguages>
